### ISSUE TITLE
RTL language strange word behavior 

### ISSUE THREAD

**Issue by amroamer** [FDVSolutions/DynamicJasper#24]
Hello @juanalvarezg ,

I am using Dynamic Jasper to create dynamic reports in Arabic language from within my web application.
I am exporting to PDF, Excel, and word. 
There is no problem when generation PDF, and Excel.

the only problem that i have is in word when generation text in Arabic it gives me a strange behavior.
lest suppose i am generating a report with the following text : "عمرو عامر الفارس"
it is printed as "الفارس عامرعمرو "
i dont know what is the problem and why its behaving like this.

please check the following [link ](https://drive.google.com/file/d/0BxgP3rykPlpLd0o2ZnJLZzRXdnc/view?usp=sharing)for an image of the behavior that i mentioned.

Thanks in advance.

**Comment by juanalvarezg** [comment]
Hi, thanks for writing.

Even seeing the image you linked, I don't understand what I'm reading.

It is supposed that JasperReports supports RTL and LTR text. How are you
setting this parameter?

By the way, it is the first time someone writes because of this problem,
so, I'm new to this as well.

Regards
Juan

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2016-02-09 10:15 GMT-03:00 Amrola <notifications@github.com>:
